In [19]:
# Data Analysis and Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
train_df=pd.read_csv('../dataset/diabetes_train.csv')
test_df=pd.read_csv('../dataset/diabetes_test.csv')

In [21]:
df=train_df.copy()

In [22]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,1,0,former,27.32,6.5,145,1
1,Female,19.0,0,0,never,25.18,4.5,126,0
2,Female,36.0,0,0,No Info,25.95,6.6,200,0
3,Female,35.0,0,0,current,23.43,6.0,159,0
4,Female,30.0,0,0,No Info,22.62,5.0,90,0

# 1.)Data Overview

In [24]:
print(f"Shape of the Training Dataset : {df.shape}")
print(f"Shape of the Test Dataset : {test_df.shape}")
print(f'Features in the dataset : {df.shape[1]}')

Shape of the Training Dataset : (80000, 9)
Shape of the Test Dataset : (20000, 9)
Features in the dataset : 9

In [28]:
print('Datatypes of the Features : ')
print('-'*45)

df.info()

Datatypes of the Features :
---------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               80000 non-null  str
 1   age                  80000 non-null  float64
 2   hypertension         80000 non-null  int64
 3   heart_disease        80000 non-null  int64
 4   smoking_history      80000 non-null  str
 5   bmi                  80000 non-null  float64
 6   HbA1c_level          80000 non-null  float64
 7   blood_glucose_level  80000 non-null  int64
 8   diabetes             80000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 5.5 MB

In [30]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,80000.0,41.900601,22.529903,0.08,24.00,43.00,60.00,80.00
hypertension,80000.0,0.074838,0.263131,0.00,0.00,0.00,0.00,1.00
heart_disease,80000.0,0.039500,0.194783,0.00,0.00,0.00,0.00,1.00
bmi,80000.0,27.316864,6.640977,10.01,23.63,27.32,29.55,95.69
HbA1c_level,80000.0,5.527534,1.070711,3.50,4.80,5.80,6.20,9.00
blood_glucose_level,80000.0,138.079013,40.662431,80.00,100.00,140.00,159.00,300.00
diabetes,80000.0,0.085000,0.278883,0.00,0.00,0.00,0.00,1.00

In [ ]:
#Useful Count distributions for some features
print(f"{df['hypertension'].value_counts()}")
print('-'*27)
print(f"{df['heart_disease'].value_counts()}")
print('-'*27)
print(f"{df['gender'].value_counts()}")
print('-'*27)
print(f"{df['smoking_history'].value_counts()}")
print('-'*27)
print(f"{df['diabetes'].value_counts()}")
print('-'*27)

hypertension
0    74013
1     5987
Name: count, dtype: int64
---------------------------
heart_disease
0    76840
1     3160
Name: count, dtype: int64
---------------------------
gender
Female    46810
Male      33174
Other        16
Name: count, dtype: int64
---------------------------
smoking_history
No Info        28579
never          28082
former          7530
current         7443
not current     5182
ever            3184
Name: count, dtype: int64
---------------------------
diabetes
0    73200
1     6800
Name: count, dtype: int64
---------------------------

In [50]:
print(f"Missing Values in the Dataset : {df.isna().sum().sum()}")

Missing Values in the Dataset : 0

In [51]:
# Count exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Total rows:", len(df))
print("Duplicate rows:", duplicate_count)
print("Duplicate percentage:", round(
    duplicate_count / len(df) * 100, 2
), "%")

Total rows: 80000
Duplicate rows: 2595
Duplicate percentage: 3.24 %

In [54]:
# View some duplicated records
df[df.duplicated(keep=False)].sort_values(
    by=df.columns.tolist()
).head(6)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
64661,Female,2.0,0,0,No Info,27.32,6.0,145,0
69354,Female,2.0,0,0,No Info,27.32,6.0,145,0
46271,Female,2.0,0,0,No Info,27.32,6.5,155,0
71950,Female,2.0,0,0,No Info,27.32,6.5,155,0
50832,Female,3.0,0,0,No Info,27.32,3.5,100,0
73948,Female,3.0,0,0,No Info,27.32,3.5,100,0